Made functional test more robust (#67)

diff --git a/.github/workflows/functional_test.yml b/.github/workflows/functional_test.yml
--- a/.github/workflows/functional_test.yml
+++ b/.github/workflows/functional_test.yml
@@ -5,7 +5,8 @@ on:
     branches: [ main, dev ]
 
 jobs:
-  build-and-test:
+  functional-test:
+    name: Functional Test
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
@@ -29,9 +30,105 @@ jobs:
     - name: Run the scraper
       run: docker compose run scraper python3 main.py --db --all-colleges --ratings
     
-    - name: Verify data exists in database
+    - name: Verify courses data exists in database
       run: |
-        RESULT=$(docker-compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify instructors data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM instructors;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify course_instructor data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM course_instructor;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify all_course_instructor_data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM all_course_instructor_data;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify metadata exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM metadata;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+
+    - name: Reset database
+      run: docker compose run scraper python3 db.py create_tables
+
+    - name: Run scraper again (to test cache)
+      run: docker compose run scraper python3 main.py --db --all-colleges --ratings
+      
+    - name: Verify courses data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify instructors data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM instructors;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify course_instructor data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM course_instructor;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify all_course_instructor_data exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM all_course_instructor_data;" | awk 'FNR == 3 {print $1}')
+        if [ "$RESULT" = "0" ]; then
+          echo "No data found in the database. Failing the pipeline."
+          exit 1
+        else
+          echo "Data successfully stored in the database. Found $RESULT records."
+        fi
+    
+    - name: Verify metadata exists in database
+      run: |
+        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM metadata;" | awk 'FNR == 3 {print $1}')
         if [ "$RESULT" = "0" ]; then
           echo "No data found in the database. Failing the pipeline."
           exit 1
