temprorarily disabled functional test and build and deployment pipeline as TMS site is being updated and testing and build and deployment will only fail

diff --git a/.github/workflows/functional_test.yml b/.github/workflows/functional_test.yml
--- a/.github/workflows/functional_test.yml
+++ b/.github/workflows/functional_test.yml
@@ -1,159 +1,159 @@
-name: Functional test
+# name: Functional test
 
-on:
-  pull_request:
-    branches: [ main, dev ]
+# on:
+#   pull_request:
+#     branches: [ main, dev ]
 
-jobs:
-  functional-test:
-    name: Functional Test
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
+# jobs:
+#   functional-test:
+#     name: Functional Test
+#     runs-on: ubuntu-latest
+#     steps:
+#     - uses: actions/checkout@v4
     
-    - name: Install Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: "3.11"
+#     - name: Install Python
+#       uses: actions/setup-python@v5
+#       with:
+#         python-version: "3.11"
     
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+#     - name: Install dependencies
+#       run: |
+#         python -m pip install --upgrade pip
+#         pip install -r requirements.txt
 
-    - name: Run mypy
-      run: mypy src --strict
+#     - name: Run mypy
+#       run: mypy src --strict
       
-    - name: Run Linter
-      run: ruff check --output-format=github src
+#     - name: Run Linter
+#       run: ruff check --output-format=github src
     
-    - name: Run Formatter
-      run: ruff format --check src
+#     - name: Run Formatter
+#       run: ruff format --check src
 
-    - name: Set up Docker Compose
-      uses: docker/setup-buildx-action@v3
+#     - name: Set up Docker Compose
+#       uses: docker/setup-buildx-action@v3
 
-    - name: Start PostgreSQL
-      run: docker-compose up -d postgres
+#     - name: Start PostgreSQL
+#       run: docker-compose up -d postgres
 
-    - name: Wait for PostgreSQL to become ready
-      run: |
-        until docker compose exec postgres pg_isready ; do
-          echo "Waiting for PostgreSQL to become ready..."
-          sleep 1
-        done
+#     - name: Wait for PostgreSQL to become ready
+#       run: |
+#         until docker compose exec postgres pg_isready ; do
+#           echo "Waiting for PostgreSQL to become ready..."
+#           sleep 1
+#         done
     
-    - name: Delete cache
-      run: rm cache/*
+#     - name: Delete cache
+#       run: rm cache/*
     
-    - name: Run the scraper
-      run: docker compose run scraper python3 src/main.py --db --all-colleges --ratings
+#     - name: Run the scraper
+#       run: docker compose run scraper python3 src/main.py --db --all-colleges --ratings
     
-    - name: Verify courses data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify courses data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify instructors data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM instructors;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify instructors data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM instructors;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify course_instructor data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM course_instructor;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify course_instructor data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM course_instructor;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify all_course_instructor_data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM all_course_instructor_data;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify all_course_instructor_data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM all_course_instructor_data;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify metadata exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM metadata;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify metadata exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM metadata;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
 
-    - name: Reset database
-      run: docker compose run scraper sh -c 'apk add postgresql-client && ./scripts/reset-db.sh;'
+#     - name: Reset database
+#       run: docker compose run scraper sh -c 'apk add postgresql-client && ./scripts/reset-db.sh;'
 
-    - name: Run scraper again (to test cache)
-      run: docker compose run scraper python3 src/main.py --db --all-colleges --ratings
+#     - name: Run scraper again (to test cache)
+#       run: docker compose run scraper python3 src/main.py --db --all-colleges --ratings
       
-    - name: Verify courses data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify courses data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM courses;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify instructors data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM instructors;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify instructors data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM instructors;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify course_instructor data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM course_instructor;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify course_instructor data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM course_instructor;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify all_course_instructor_data exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM all_course_instructor_data;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify all_course_instructor_data exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM all_course_instructor_data;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Verify metadata exists in database
-      run: |
-        RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM metadata;" | awk 'FNR == 3 {print $1}')
-        if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
-          echo "No data found in the database. Failing the pipeline."
-          exit 1
-        else
-          echo "Data successfully stored in the database. Found $RESULT records."
-        fi
+#     - name: Verify metadata exists in database
+#       run: |
+#         RESULT=$(docker compose exec postgres psql -U postgres -d postgres -c "SELECT COUNT(*) FROM metadata;" | awk 'FNR == 3 {print $1}')
+#         if [ -z "$RESULT" ] || [ "$RESULT" = "0" ]; then
+#           echo "No data found in the database. Failing the pipeline."
+#           exit 1
+#         else
+#           echo "Data successfully stored in the database. Found $RESULT records."
+#         fi
     
-    - name: Cleanup
-      run: docker-compose down -v
+#     - name: Cleanup
+#       run: docker-compose down -v
